# stylish-haskell configuration file
# See: https://github.com/jaspervdj/stylish-haskell/blob/master/data/stylish-haskell.yaml
steps:
  - imports:
      align: group
  - language_pragmas:
      style: vertical
      remove_redundant: true
  - records: {}
  - trailing_whitespace: {}
columns: 79
language_extensions:
  - LambdaCase
